### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by AnHardt** [eboston/Adafruit-ST7565-Full-Graphic-Controller#2]
Wouldn't it be a good ides to provide some pictures?
Maybe not actually your test hardware, but the schemes and layout.
This way you have not to install eagle to get an impression.

**Comment by eboston** [comment]
It's coming.  Had some other issues come up and haven't been able to finish adding items.

BTW, there is an image of the schematics already.

**Comment by AnHardt** [comment]
Somehow missed it.
